- hosts: all
  tasks:
  - name: Set hostname
    become: yes
    hostname:
      name: "{{ inventory_hostname_short }}"

  - name: Set localhost
    become: yes
    lineinfile:
      dest: "/etc/hosts"
      state: "present"
      regexp: "^127.0.0.1 +localhost"
      line: "127.0.0.1    localhost {{ inventory_hostname_short }}"

  - name: Use vi as a default editor
    become: yes
    lineinfile:
      dest: "/etc/bash.bashrc"
      state: "present"
      regexp: "EDITOR="
      line: "export EDITOR=vi"

  - name: Define ll
    become: yes
    lineinfile:
      dest: "/etc/bash.bashrc"
      state: "present"
      regexp: "alias ll="
      line: "alias ll='ls -la'"

  - name: modify bashrc
    blockinfile:
      path: "{{ ansible_env.HOME }}/.bashrc"
      block: "{{ lookup('file', './files/bashrc') }}"

  - name: copy tmux.conf
    copy:
      src: tmux.conf
      dest: "{{ ansible_env.HOME }}/.tmux.conf"

  - name: apt upgrade
    become: yes
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install apt packages
    become: yes
    apt:
      update_cache: yes
      state: latest
      name:
        - git
        - git-flow
        - tmux
        - emacs-nox
        - ispell
        - python-dev
        - python3-dev
        - python3-pip
        - python-smbus
        - i2c-tools
        - libi2c-dev
        - pigpio

  - name: Install pip packages
    pip:
      executable: pip3
      state: latest
      name:
        - 'python-language-server[all]'
        - pyls-isort
        - pyls-mypy
        - pyls-black
        - pyls-memestra
        - autoflake
        - importmagic
        - epc
        - flake8-black
        - flake8-isort
        - pylint
        - pigpio

  - name: Enable I2C
    become: yes
    command: "raspi-config nonint do_i2c 0"

  - name: Enable SPI
    become: yes
    command: "raspi-config nonint do_spi 0"

  - name: Enable pigpiod
    become: yes
    command: "systemctl enable pigpiod"

  - name: Install spacemacs
    git:
      repo: https://github.com/syl20bnr/spacemacs
      dest: "{{ ansible_env.HOME }}/.emacs.d"
      version: develop

  - block:
    - name: Set python3 as a default
      file:
        state: link
        src: /usr/bin/python3
        dest: /usr/bin/python
    - name: Set pip3 as a default
      file:
        state: link
        src: /usr/bin/pip3
        dest: /usr/bin/pip
    become: yes

  - name: reboot
    become: yes
    reboot:
